title: Association of Women Who Develop Software
email: rhildred@gmail.com
description: >-
  Professional development for software developers working in survival mode. I
  am not even sure of the name of the association yet.
baseurl: ''
url: 'https://ysaas.ca'
twitter_username: rhildred
github_username: rhildred
markdown: kramdown
disqus:
  shortname: ysaas
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-seo-tag
collections:
  CIW:
    output: true
    permalink: '/CIW/:path/'
  Courses_Survey:
    output: true
    permalink: '/Courses_Survey/:path/'
exclude:
  - jekyll-admin
