title: Association of Women Who Develop Software
email: rhildred@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: rhildred
github_username: rhildred
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-seo-tag
collections:
  CIW:
    output: true
    permalink: /CIW/:path/
  Courses_Survey:
    output: true
    permalink: /Courses_Survey/:path/
exclude:
  - 'jekyll-admin'
